[package]
name = "sketchmotion"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Único crate que compõe os demais.
sketchmotion-render = { path = "../render" }
# Janela + UI em modo imediato (eframe já traz o egui junto via eframe::egui).
eframe = "0.29"
