[package]
name = "sketchmotion"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sketchmotion-core = { path = "../core" }
sketchmotion-render = { path = "../render" }
sketchmotion-tools = { path = "../tools" }
sketchmotion-color = { path = "../color" }
sketchmotion-io = { path = "../io" }
eframe = "0.29"
rfd = "0.14"
